version: '3.8'

services:
  client:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client/dist:/app/client/dist
    depends_on:
      - server

  server:
    build:
      context: .
      target: production
    ports:
      - "5008:5008"
    environment:
      - NODE_ENV=production
      - PORT=5008
    volumes:
      - ./server/dist:/app/server/dist

  development:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "5008:5008"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
    command: npm run dev